services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    image: frontend
    container_name: client-container
    volumes:
      - ./src:/src
      - ./public:/public
    ports:
      - "3000:3000"
    environment:
     - CHOKIDAR_USEPOLLING=true  
     - WATCHPACK_POLLING=true  
    
